[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.0.0",
    "pytest>=8.4.1",
    "pytest-benchmark>=5.1.0",
]
